dict_iucn3_1 = {
"1":"Forest & Woodland",
"1.1":"Boreal Forest",
"1.2":"Subarctic Forest",
"1.3":"Subantarctic Forest",
"1.4":"Temperate Forest",
"1.5":"Subtropical/Tropical Dry Forest",
"1.6":"Subtropical/Tropical Moist Lowland Forest",
"1.7":"Subtropical/Tropical Mangrove Forest Vegetation Above High Tide Level",
"1.8":"Subtropical/Tropical Swamp Forest",
"1.9":"Subtropical/Tropical Moist Montane Forest",
"2":"Savanna",
"2.1":"Dry Savanna",
"2.2":"Moist Savanna",
"3":"Shrubland",
"3.1":"Subarctic Shrubland",
"3.2":"Subantarctic Shrubland",
"3.3":"Boreal Shrubland",
"3.4":"Temperate Shrubland",
"3.5":"Subtropical/Tropical Dry Shrublan",
"3.6":"Subtropical/Tropical Moist Shrublan",
"3.7":"Subtropical/Tropical High Altitude Shrubland",
"3.8":"Mediterranean-type Shrubby Vegetation",
"4":"Native Grassland",
"4.1":"Tundra",
"4.2":"Subarctic Grassland",
"4.3":"Subantarctic Grassland",
"4.4":"Temperate Grassland",
"4.5":"Subtropical/Tropical Dry Lowland Grassland",
"4.6":"Subtropical/Tropical Seasonally Wet/Flooded Lowland Grassland",
"4.7":"Subtropical/Tropical High Altitude Grassland",
"5":"Wetlands(Inland)",
"5.1":"Permanent Rivers, Streams, Creeks",
"5.2":"Seasonal/Intermittent/Irregular Rivers, Streams, Creek",
"5.3":"Shrub Dominated Wetlands",
"5.4":"Bogs, Marshes, Swamps, Fens, Peatlands",
"5.5":"Permanent Freshwater Lakes",
"5.6":"Seasonal/Intermittent  Freshwater Lakes",
"5.7":"Permanent  Freshwater Marshes/Pools",
"5.8":"Seasonal/Intermittent  Freshwater Marshes/Pools",
"5.9":"Freshwater Springs and Oases",
"5.1":"Tundra Wetlands",
"5.11":"Alpine Wetlands",
"5.12":"Geothermal Wetlands",
"5.13":"Permanent Inland Deltas",
"5.14":"Permanent Saline, Brackish or Alkaline Lakes",
"5.15":"Seasonal/Intermittent Saline, Brackish or Alkaline Lakes and Flats",
"5.16":"Permanent Saline, Brackish or Alkaline Marshes/Pools",
"5.17":"Seasonal/Intermittent Saline, Brackish or Alkaline Marshes/Pools",
"5.18":"Karst and Other Subterranean Inland Aquatic Systems",
"6":"Inland Rocky Areas",
"7":"Caves & Subterranean Habitats",
"7.1":"Dry Caves",
"7.2":"Other Dry Subterranean Habitats",
"8":"Desert",
"8.1":"Hot Desert",
"8.2":"Temperate Desert",
"8.3":"Cold Desert",
"9":"Marine - Neritic",
"9.1":"Pelagic",
"9.2":"Subtidal Rock and Rocky Reefs",
"9.3":"Subtidal Loose Rock/Pebble/Gravel",
"9.4":"Subtidal Sandy",
"9.5":"Subtidal Sandy-Mud",
"9.6":"Subtidal Muddy",
"9.7":"Macroalgal/Kelp",
"9.8":"Coral Reef",
"9.8.1":"Outer Reef Channel",
"9.8.2":"Back Slope",
"9.8.3":"Foreslope (Outer Reef Slope)",
"9.8.4":"Lagoon",
"9.8.5":"Inter-reef Soft Substrate",
"9.8.6":"Inter-reef Rubble Substrate",
"9.9":"Seagrass (submerged)",
"9.1":"Estuaries",
"10":"Marine - Oceanic",
"10.1":"Epipelagic (0–200 m)",
"10.2":"Mesopelagic (200–1,000 m)",
"10.3":"Bathypelagic (1,000–4,000 m)",
"10.4":"Abyssopelagic (4,000–6,000 m)",
"11":"Marine - Deep Ocean Floor(Benthic and Demersal)",
"11.1":"Continental Slope/Bathyl zone (200–4,000 m)",
"11.1.1":"Hard Substrate",
"11.1.2":"Soft Substrate",
"11.2":"Abyssal Plain (4,000–6,000 m)",
"11.3":"Abyssal Mountain/Hills (4,000–6,000m)",
"11.4":"Hadal/Deep Sea Trench (>6000 m)",
"11.5":"Seamount",
"11.6":"Deep Sea Vents (Rifts/Seeps)",
"12":"Marine - Intertidal",
"12.1":"Rocky Shoreline",
"12.2":"Sandy Shorelines and/or Beaches, Sand Bars, Spits,etc.",
"12.3":"Shingle and/or Pebble Shoreline and/or Beaches",
"12.4":"Mud Shoreline and Intertidal Mud Flats",
"12.5":"Salt Marshes (Emergent Grasses)",
"12.6":"Tidepools",
"12.7":"Mangrove Submerged Roots",
"13":"Marine - Coastal/Supratidal",
"13.1":"Sea Cliffs and Rocky Offshore Islands",
"13.2":"Coastal Caves/Karst",
"13.3":"Coastal Sand Dunes",
"13.4":"Coastal Brackish/Saline Lagoons/Marine Lakes",
"13.5":"Coastal Freshwater Lakes",
"14":"Artificial - Terrestrial",
"14.1":"Arable Land",
"14.2":"Pastureland",
"14.3":"Plantations",
"14.4":"Rural Gardens",
"14.5":"Urban Areas",
"14.6":"Subtropical/Tropical Heavily Degraded Former Forest",
"15":"Artificial - Aquatic",
"15.1":"Water Storage Areas",
"15.2":"Ponds",
"15.3":"Aquaculture Ponds",
"15.4":"Salt Exploitation Sites",
"15.5":"Excavations (open)",
"15.6":"Wastewater Treatment Areas",
"15.7":"Irrigated Land",
"15.8":"Seasonally Flooded Agricultural Land",
"15.9":"Canals and Drainage Channels, Ditches",
"15.1":"Karst and Other Subterrranean Hydrological Systems",
"15.11":"Marine Anthropogenic Structures",
"15.12":"Mariculture Cages",
"15.13":"Mari/Brackish-culture Ponds",
"16":"Introduced Vegetation",
"17":"Other",
"18":"Unknown"}